### ISSUE TITLE
パイプの並び順がシャッフルされ使いにくい

### ISSUE THREAD

**Issue by robo37** [Gakuto1112/Stormworks-JapaneseTranslation#18]
毎回更新ありがとうございます。
コンポーネント名の英語併記のアップデートよりパーツリストでの並び順が変化し、特にパイプ系の(Enclosed)がアルファベット順を無視しているのかほぼシャッフル状態です。
併記アプデ以前は今の英語版のような並び順だったためパーツ名の表記を <日本語名> | <英語名> にするなど修正お願いしたいです。

**Comment by Gakuto1112** [comment]
報告ありがとうございます。

StormworksのコンポーネントリストはUnicode順で並ぶ仕様があります。ゲーム内言語が英語だろうが日本語だろうがコンポーネントの並び順が一緒になるという意図で、英語 → 日本語の順で記載していました。しかし、区切り文字として"|"を使用しているので、括弧表記より並び順が先になっているようですね。

対策としては、区切り文字を別のものに変更するというものがありますね。検討します。

**Comment by Gakuto1112** [comment]
> 対策としては、区切り文字を別のものに変更するというものがありますね。検討します。

と考えて検証したのですが、どうも上手くいかないようです。これは恐らく日本語 → 英語の順で併記しても発生しそうです。

**Comment by Gakuto1112** [comment]
@robo37 
とりあえず日本語と英語をひっくり返したバージョンを用意しましたので試してみてください。以下のリンク先の「Artifacts」にあるファイルを拾ってください。

https://github.com/Gakuto1112/Stormworks-JapaneseTranslation/actions/runs/9599022375

ファイルを展開した後、`":\Users\<user_name>\AppData\Roaming\Stormworks\data\languages\"に`japanese.tsv`と`japanese.xml`を入れてください（パスは自身の環境に応じて変更してください）。その後、ゲームの設定画面内の「言語」タブから、「保存済み」欄にある「japanese」を選んで適用してください。

![screenshot](https://github.com/Gakuto1112/Stormworks-JapaneseTranslation/assets/90630001/4aba22a5-2759-4a08-9d52-f8a4987cf02e)

**Comment by Gakuto1112** [comment]
他の方の意見を伺うために、Discordの #翻訳 チャンネルでアンケート調査を開始しました。1週間ほどを期限として様子を伺います。

https://discord.com/channels/528761500341370880/544673070124630017/1253922433073811526
（上記リンクのメッセージから始まる、一連の会話がアンケートに該当します。）

**Comment by Gakuto1112** [comment]
投票が終了しました。以下が投票結果です。

> Q. ローカライゼーション適用後のコンポーネントの並び順について、あなたはこの並び順が使いにくいと感じますか？（13票）
> 1. 🤨 以前から使いにくいと感じる（5票、38%）
> 2. 🤔 別に使いにくいとは感じなかったが、これを聞いて改めてそう感じた（4票、31%）
> 3. 🙂 別に使いにくいとは感じれいない（4票、31%）

> Q. 「英語と日本語をひっくり返したもの（新しい方）」と以前のものを比較してどちらの方がよいですか？ （主にコンポーネントの並び順についてご注目ください。）（11票）
> 1. 🆕 新しい方（11票、100%）
> 2. 🟦 以前の方（0票、0%）

投票数は少ないけど、民主主義ってことで、採択する方向で進めます。

**Comment by Gakuto1112** [comment]
v1.11.0-bで採択しました。
