### ISSUE TITLE
"crankshaft" の和訳について

### ISSUE THREAD

**Issue by jinnosukeKato** [Gakuto1112/Stormworks-JapaneseTranslation#4]
"crankshaft"の和訳が「主軸」となっていますが、一般的には「クランクシャフト」、カタカナを使用しないのであれば、「曲軸」が適切かつ理解しやすいかと思います。
もし何か意図があり現在の和訳を当てているのなら申し訳ないです。

**Comment by Gakuto1112** [comment]
ご指摘ありがとうございます。改めて検索したところ、確かに"crankshaft"の訳としての「主軸」は、間違っていないのかもしれませんが、あまり使われていないようでした。これを踏まえて、"crankshaft"の訳を「クランクシャフト」なり「曲軸」なりに変えようかと思います。

**Comment by Gakuto1112** [comment]
先程リリースしたバージョンにて、（試験的に）"crankshaft"の訳を「クランクシャフト」に変更しました。
