### ISSUE TITLE
一部のパイプの説明欄がバグっている

### ISSUE THREAD

**Issue by jinnosukeKato** [Gakuto1112/Stormworks-JapaneseTranslation#5]
直線、角以外の通常パイプと角分岐、T字のブロック型パイプの説明欄に`def_trans_***`という文章が混入しています

**Comment by Gakuto1112** [comment]
報告ありがとうございます。只今、該当の不具合を確認しました。今から修正に取り掛かります。

**Comment by Gakuto1112** [comment]
報告頂いた不具合は、こちらの不具合ではなく、ゲームの不具合のようです。`def_trans_***`に対応する翻訳データが、何故か欠落しており、こちら側では何も出来ないようです。

この症状は英語でも確認出来ました。

![英語表記での不具合](https://user-images.githubusercontent.com/90630001/203541226-d5eaf9d2-c01a-42ab-8295-7cc2ba2256a9.jpg)
