### ISSUE TITLE
Submitについて

### ISSUE THREAD

**Issue by mumeinosato** [Gakuto1112/Stormworks-JapaneseTranslation#6]
595行目のSubmitがマルチプレイでパスワードの入力の確定でも使用されているのでOKなどに変えてもいいと思う。
![スクリーンショット (201)](https://github.com/Gakuto1112/Stormworks-JapaneseTranslation/assets/66110797/37defa06-2eb0-4dd3-a5db-9752c54755b9)

**Comment by Gakuto1112** [comment]
ありがとうございます。他で使われている場所とも考慮して、検討します。

**Comment by Gakuto1112** [comment]
大変遅くなりましたが、提案の方を採用させて頂きました。ありがとうございます。

**Comment by Gakuto1112** [comment]
v1.8.10-1.0にて採用
